In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score
from scipy.spatial.distance import cdist
import json

In [51]:
df = pd.read_csv("working_data.csv")

# Separate descriptors and target
player_descriptors = df.iloc[:, :3]
league = df['Lg']
cy_young_place = df['Cy_young']
X = df.iloc[:, 3:-1]

# Add league temporarily for sorting
X['Lg'] = league
y = cy_young_place

# Create separate datasets
x_al = X[X['Lg'] == 'AL'].drop(columns=['Lg'])
x_nl = X[X['Lg'] == 'NL'].drop(columns=['Lg'])

y_al = y[league == 'AL']
y_nl = y[league == 'NL']


The following is done using cdist and euclidean distances, without selecting any attributes

In [52]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler_nl = MinMaxScaler()
X_nl_scaled = scaler_nl.fit_transform(x_nl)

scaler_al = MinMaxScaler()
X_al_scaled = scaler_al.fit_transform(x_al)

In [53]:
#NL cdist
x_nl_dist = cdist(X_nl_scaled,X_nl_scaled, metric='euclidean')
#AL cdist
x_al_dist = cdist(X_al_scaled,X_al_scaled, metric='euclidean')

print("NL distance: \n", x_nl_dist)
print("AL distance: \n", x_al_dist)

NL distance: 
 [[0.         0.98695817 0.56775318 ... 2.23652283 1.8199935  2.16903755]
 [0.98695817 0.         1.03209955 ... 2.07810409 1.75828245 2.11737208]
 [0.56775318 1.03209955 0.         ... 1.97678025 1.54167331 1.96272459]
 ...
 [2.23652283 2.07810409 1.97678025 ... 0.         1.1837118  0.65915191]
 [1.8199935  1.75828245 1.54167331 ... 1.1837118  0.         1.08374042]
 [2.16903755 2.11737208 1.96272459 ... 0.65915191 1.08374042 0.        ]]
AL distance: 
 [[0.         1.16213957 1.33382651 ... 1.6825858  1.92145488 2.06929937]
 [1.16213957 0.         1.1494366  ... 1.79586316 2.00766221 2.33398518]
 [1.33382651 1.1494366  0.         ... 2.0490732  2.24144284 2.26030779]
 ...
 [1.6825858  1.79586316 2.0490732  ... 0.         0.55228623 0.96820896]
 [1.92145488 2.00766221 2.24144284 ... 0.55228623 0.         0.90288181]
 [2.06929937 2.33398518 2.26030779 ... 0.96820896 0.90288181 0.        ]]


In [54]:
print("NL Predictions")
#predict NL
for i in range(len(x_nl_dist)):
  x_nl_dist[i,i] = np.inf
  index = np.argmin(x_nl_dist[i])
  x_nl_dist[i,i] = 0
  predict_class = y_nl.iloc[index]
  print(predict_class)

print("AL predictions")
#predict AL
for i in range(len(x_al_dist)):
  x_al_dist[i,i] = np.inf
  index = np.argmin(x_al_dist[i])
  x_al_dist[i,i] = 0
  predict_class = y_al.iloc[index]
  print(predict_class)

NL Predictions
11
0
0
0
5
6
3
6
0
0
0
5
4
4
7
2
11
3
0
2
6
8
10
2
2
1
10
8
2
6
2
3
5
3
0
1
0
0
4
6
0
4
0
2
5
7
1
1
3
0
3
0
0
11
0
0
0
0
0
0
0
0
0
0
0
6
0
5
0
1
0
0
0
0
0
0
3
0
0
0
10
0
0
0
2
0
0
0
8
0
0
0
0
0
0
0
0
0
0
11
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
0
0
0
0
0
0
4
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
AL predictions
6
0
0
0
0
5
0
7
3
6
4
3
0
0
0
9
4
4
8
0
6
8
3
0
0
6
6
7
6
0
3
8
3
0
9
3
6
4
0
2
4
5
1
1
7
0
0
3
0
0
0
0
0
0
0
0
0
0
0
6
0
0
10
0
0
0
0
0
0
0
0
0
0
0
0
0
0
9
0
4
0
0
0
0
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [55]:
# Read selected features (from forest importance)
with open('forest_importance_nl.json', 'r') as f:
    selected_features_nl_importance = json.load(f)

with open('forest_importance_al.json', 'r') as f:
    selected_features_al_importance = json.load(f)

# Read selected features (from Chi-squared)
with open('chi2_selected_features_nl.json', 'r') as f:
    selected_features_nl_chi2 = json.load(f)


with open('chi2_selected_features_al.json', 'r') as f:
    selected_features_al_chi2 = json.load(f)

In [56]:
#Random Forest Importance
x_nl_importance = x_nl[selected_features_nl_importance]
x_al_importance = x_al[selected_features_al_importance]

# Chi-squared Features
x_nl_chi2 = x_nl[selected_features_nl_chi2]
x_al_chi2 = x_al[selected_features_al_chi2]


After selecting attributes, We will begin to use KNearestNeighbor classifier

In [57]:
#Scale with MinMax
scaler_nl_importance = MinMaxScaler()
X_nl_importance_min_max = scaler_nl_importance.fit_transform(x_nl_importance)

scaler_al_importance = MinMaxScaler()
X_al_importance_min_max = scaler_al_importance.fit_transform(x_al_importance)

scaler_nl_chi2 = MinMaxScaler()
X_nl_chi2_min_max = scaler_nl_chi2.fit_transform(x_nl_chi2)

scaler_al_chi2 = MinMaxScaler()
X_al_chi2_min_max = scaler_al_chi2.fit_transform(x_al_chi2)

In [58]:
#KNN with min max
k = 10
#NL importance
knn_nl_importance = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_nl_importance.fit(X_nl_importance_min_max, y_nl)

y_pred_nl_importance = knn_nl_importance.predict(X_nl_importance_min_max)
print("Importance NL Predictions: \n", y_pred_nl_importance)

#AL Importance
knn_al_importance = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_al_importance.fit(X_al_importance_min_max, y_al)

y_pred_al_importance = knn_al_importance.predict(X_al_importance_min_max)
print("Importance AL Predictions: \n", y_pred_al_importance)

#NL Chi2
knn_nl_chi2 = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_nl_chi2.fit(X_nl_chi2_min_max, y_nl)

y_pred_nl_chi2 = knn_nl_chi2.predict(X_nl_chi2_min_max)
print("Chi2 NL Predictions: \n", y_pred_nl_chi2)

#AL Chi2
knn_al_chi2 = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_al_chi2.fit(X_al_chi2_min_max, y_al)

y_pred_al_chi2 = knn_al_chi2.predict(X_al_chi2_min_max)
print("Chi2 AL Predictions: \n", y_pred_al_chi2)

Importance NL Predictions: 
 [11 11 11 11 10 10  9  9  8  8  8  8  7  7  7  7  7  7  6  6  6  6  6  5
  5  5  5  5  4  4  4  4  4  3  3  3  3  3  2  2  2  2  2  1  1  1  1  1
 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0 

In [59]:
#Model Evaluation
k = 15
#Importance Models
kf_nl_importance = KFold(n_splits=k, shuffle=True, random_state=42)
scores_nl_importance = cross_val_score(knn_nl_importance, X_nl_importance_min_max , y_nl, cv=kf_nl_importance)
print(f"Accuracy scores for each fold NL Importance: {scores_nl_importance}")
print(f"Average accuracy for NL Importance: {np.mean(scores_nl_importance):.4f}")

kf_al_importance = KFold(n_splits=k, shuffle=True, random_state=42)
scores_al_importance = cross_val_score(knn_al_importance, X_al_importance_min_max , y_al, cv=kf_nl_importance)
print(f"Accuracy scores for each fold AL Importance: {scores_al_importance}")
print(f"Average accuracy for AL Importance: {np.mean(scores_al_importance):.4f}")

#Chi2 Models
kf_nl_chi2 = KFold(n_splits=k, shuffle=True, random_state=42)
scores_nl_chi2 = cross_val_score(knn_nl_chi2, X_nl_chi2_min_max , y_nl, cv=kf_nl_chi2)
print(f"Accuracy scores for each fold NL Chi2: {scores_nl_chi2}")
print(f"Average accuracy for NL Chi2: {np.mean(scores_nl_chi2):.4f}")

kf_al_chi2 = KFold(n_splits=k, shuffle=True, random_state=42)
scores_al_chi2 = cross_val_score(knn_al_chi2, X_al_chi2_min_max , y_al, cv=kf_al_chi2)
print(f"Accuracy scores for each fold AL Chi2: {scores_al_chi2}")
print(f"Average accuracy for AL Chi2: {np.mean(scores_al_chi2):.4f}")

Accuracy scores for each fold NL Importance: [0.875      0.75       0.875      0.875      0.79166667 0.91666667
 0.875      0.875      0.91304348 0.7826087  0.7826087  0.86956522
 0.82608696 0.86956522 0.95652174]
Average accuracy for NL Importance: 0.8556
Accuracy scores for each fold AL Importance: [0.8        0.8        0.96       0.84       0.84       0.91666667
 0.95833333 0.91666667 0.875      0.875      0.83333333 0.83333333
 0.875      0.91666667 0.95833333]
Average accuracy for AL Importance: 0.8799
Accuracy scores for each fold NL Chi2: [0.875      0.75       0.875      0.875      0.79166667 0.91666667
 0.91666667 0.875      0.86956522 0.82608696 0.7826087  0.82608696
 0.82608696 0.86956522 0.95652174]
Average accuracy for NL Chi2: 0.8554
Accuracy scores for each fold AL Chi2: [0.8        0.8        0.96       0.84       0.84       0.91666667
 0.91666667 0.91666667 0.91666667 0.875      0.83333333 0.83333333
 0.875      0.91666667 0.95833333]
Average accuracy for AL Chi2: 0.8

We already have prediction classes here, but again I will be using f1 score

In [60]:
#Now we can use f1 to show the relation between precision and recall

f1_nl_importance = f1_score(y_nl, y_pred_nl_importance, average='macro')
print("F1 Score NL Importance:", f1_nl_importance)

f1_al_importance = f1_score(y_al, y_pred_al_importance, average='macro')
print("F1 Score AL Importance:", f1_al_importance)

f1_nl_chi2 = f1_score(y_nl, y_pred_nl_chi2, average='macro')
print("F1 Score NL Chi2:", f1_nl_chi2)

f1_al_chi2 = f1_score(y_al, y_pred_al_chi2, average='macro')
print("F1 Score AL Chi2:", f1_al_chi2)

F1 Score NL Importance: 1.0
F1 Score AL Importance: 1.0
F1 Score NL Chi2: 1.0
F1 Score AL Chi2: 1.0


Above we made a mistake and evaluated the model by comparing something we've already fit to the model so it predicts it perfectly almost always. Below we will use train test split to minimize this risk

In [61]:
k = 2

# Train-test split for Importance
#NL
X_train_nl, X_test_nl, y_train_nl, y_test_nl = train_test_split(X_nl_importance_min_max, y_nl, test_size=0.2, random_state=42)

knn_nl_importance = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_nl_importance.fit(X_train_nl, y_train_nl)
y_pred_nl_importance = knn_nl_importance.predict(X_test_nl)

f1_nl_importance = f1_score(y_test_nl, y_pred_nl_importance, average='macro')
print("F1 Score NL Importance:", f1_nl_importance)

# AL
X_train_al, X_test_al, y_train_al, y_test_al = train_test_split(X_al_importance_min_max, y_al, test_size=0.2, random_state=42)

knn_al_importance = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_al_importance.fit(X_train_al, y_train_al)
y_pred_al_importance = knn_al_importance.predict(X_test_al)

f1_al_importance = f1_score(y_test_al, y_pred_al_importance, average='macro')
print("F1 Score AL Importance:", f1_al_importance)

# Train-tests split for Chi2
#NL
X_train_nl_chi2, X_test_nl_chi2, y_train_nl_chi2, y_test_nl_chi2 = train_test_split(X_nl_chi2_min_max, y_nl, test_size=0.2, random_state=42)

knn_nl_chi2 = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_nl_chi2.fit(X_train_nl_chi2, y_train_nl_chi2)
y_pred_nl_chi2 = knn_nl_chi2.predict(X_test_nl_chi2)

f1_nl_chi2 = f1_score(y_test_nl_chi2, y_pred_nl_chi2, average='macro')
print("F1 Score NL Chi2:", f1_nl_chi2)

# AL
X_train_al_chi2, X_test_al_chi2, y_train_al_chi2, y_test_al_chi2 = train_test_split(X_al_chi2_min_max, y_al, test_size=0.2, random_state=42)

knn_al_chi2 = KNeighborsClassifier(n_neighbors=k, metric='euclidean', weights='distance')
knn_al_chi2.fit(X_train_al_chi2, y_train_al_chi2)
y_pred_al_chi2 = knn_al_chi2.predict(X_test_al_chi2)

f1_al_chi2 = f1_score(y_test_al_chi2, y_pred_al_chi2, average='macro')
print("F1 Score AL Chi2:", f1_al_chi2)


F1 Score NL Importance: 0.1318181818181818
F1 Score AL Importance: 0.1334776334776335
F1 Score NL Chi2: 0.08715251690458302
F1 Score AL Chi2: 0.09606299212598425


Did more research on how to control and correctly classify a dataset with highly imbalanced classes, as KNN relies on neighbors, but all MLB pitchers aer at a professional level and there is only 1 Cy Young winner. However, most of the research dives into models we haven't worked with so we will just mention this in our write up.

In [90]:
# Prep test data
df_test = pd.read_csv("test_data.csv")

player_descriptors_test = df_test.iloc[:, :3]
league = df_test['Lg']
x_test = df_test.iloc[:, 3:-1]

player_descriptors_nl = player_descriptors_test[league == 'NL'].reset_index(drop=True)
player_descriptors_al = player_descriptors_test[league == 'AL'].reset_index(drop=True)

# Add league temporarily for sorting
x_test['Lg'] = league

# Create separate datasets
x_al_test = x_test[x_test['Lg'] == 'AL'].drop(columns=['Lg'])
x_nl_test = x_test[x_test['Lg'] == 'NL'].drop(columns=['Lg'])

In [91]:
#Random Forest Importance
x_nl_importance_test = x_nl_test[selected_features_nl_importance]
x_al_importance_test = x_al_test[selected_features_al_importance]

# Chi-squared Features
x_nl_chi2_test = x_nl_test[selected_features_nl_chi2]
x_al_chi2_test = x_al_test[selected_features_al_chi2]

print(x_al_importance_test)

     WAR    SO    FIP   ERA+    IP    ERA     BF    W   WHIP   GS
0    1.7  38.0   3.67  112.0  49.2   3.62  208.0  1.0  1.208  8.0
1    1.4  56.0   2.80  206.0  49.0   2.02  196.0  3.0  1.061  8.0
2    1.2  57.0   3.56  134.0  48.2   2.96  188.0  4.0  0.925  8.0
6    1.5  39.0   2.91  394.0  44.2   1.01  181.0  6.0  0.940  7.0
8    1.1  34.0   4.47  133.0  44.0   3.07  171.0  3.0  1.045  7.0
..   ...   ...    ...    ...   ...    ...    ...  ...    ...  ...
551  0.0   1.0   4.06   61.0   1.0   9.00    6.0  0.0  3.000  0.0
552 -0.3   0.0  19.06   30.0   1.0  18.00    7.0  0.0  5.000  0.0
553 -0.1   0.0  22.06   15.0   1.0  36.00    7.0  0.0  3.000  0.0
554 -0.2   0.0  25.06   12.0   1.0  45.00   11.0  0.0  7.000  0.0
566  0.0   0.0  12.06    NaN   0.1   0.00    2.0  0.0  3.000  0.0

[193 rows x 10 columns]


In [92]:
scaler_nl_importance = MinMaxScaler()
scaler_nl_importance.fit(x_nl_importance)
x_nl_imp_scaled_test = scaler_nl_importance.transform(x_nl_importance_test)

scaler_al_importance = MinMaxScaler()
scaler_al_importance.fit(x_al_importance)
x_al_imp_scaled_test = scaler_al_importance.transform(x_al_importance_test)

scaler_nl_chi2 = MinMaxScaler()
scaler_nl_chi2.fit(x_nl_chi2)
x_nl_chi2_scaled_test = scaler_nl_chi2.transform(x_nl_chi2_test)

scaler_al_chi2 = MinMaxScaler()
scaler_al_chi2.fit(x_al_chi2)
x_al_chi2_scaled_test = scaler_al_chi2.transform(x_al_chi2_test)


In [93]:
#Impute to handle NaN data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

# Impute all four test sets
x_nl_imp_scaled_test = imputer.fit_transform(x_nl_imp_scaled_test)
x_al_imp_scaled_test = imputer.fit_transform(x_al_imp_scaled_test)
x_nl_chi2_scaled_test = imputer.fit_transform(x_nl_chi2_scaled_test)
x_al_chi2_scaled_test = imputer.fit_transform(x_al_chi2_scaled_test)


In [94]:
#predict test set
y_pred_nl_importance = knn_nl_importance.predict(x_nl_imp_scaled_test)
y_pred_al_importance = knn_al_importance.predict(x_al_imp_scaled_test)
y_pred_nl_chi2 = knn_nl_chi2.predict(x_nl_chi2_scaled_test)
y_pred_al_chi2 = knn_al_chi2.predict(x_al_chi2_scaled_test)


In [98]:
# Calculate distances from test points to nearest neighbors
distances_imp_nl, _ = knn_nl_importance.kneighbors(x_nl_imp_scaled_test, n_neighbors=1)
distances_imp_al, _ = knn_al_importance.kneighbors(x_al_imp_scaled_test, n_neighbors=1)
distances_chi2_nl, _ = knn_nl_importance.kneighbors(x_nl_chi2_scaled_test, n_neighbors=1)
distances_chi2_al, _ = knn_al_importance.kneighbors(x_al_chi2_scaled_test, n_neighbors=1)

def select_winner(winner_mask, distances, descriptors):
    indices = list(np.where(winner_mask)[0])
    if indices:
        best_index = min(indices, key=lambda i: distances[i][0])
    else:
        best_index = np.argmin(distances)
    return descriptors.iloc[best_index]

# Importance
nl_winner_imp = select_winner(nl_importance_winners, distances_imp_nl, player_descriptors_nl)
al_winner_imp = select_winner(al_importance_winners, distances_imp_al, player_descriptors_al)

# Chi2
nl_winner_chi2 = select_winner(nl_chi2_winners, distances_chi2_nl, player_descriptors_nl)
al_winner_chi2 = select_winner(al_chi2_winners, distances_chi2_al, player_descriptors_al)

# Importance Output
print("🏆 Predicted NL Cy Young (Importance features):")
print(nl_winner_imp)

print("\n🏆 Predicted AL Cy Young (Importance features):")
print(al_winner_imp)

# Chi2 Output
print("🏆 Predicted NL Cy Young (Chi2 features):")
print(nl_winner_chi2)

print("\n🏆 Predicted AL Cy Young (Chi2 features):")
print(al_winner_chi2)


🏆 Predicted NL Cy Young (Importance features):
Player    MacKenzie Gore*
yr                   25.0
Team                  WSN
Name: 1, dtype: object

🏆 Predicted AL Cy Young (Importance features):
Player    Luis Severino
yr                 25.0
Team                ATH
Name: 0, dtype: object
🏆 Predicted NL Cy Young (Chi2 features):
Player    MacKenzie Gore*
yr                   25.0
Team                  WSN
Name: 1, dtype: object

🏆 Predicted AL Cy Young (Chi2 features):
Player    Carlos Rodón*
yr                 25.0
Team                NYY
Name: 2, dtype: object
